import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Card, SectionHeading } from './primitives';
import { colors, employmentColors, font, shadow } from '@/constants/theme';
import { MAIN_ALLOWANCES, type Employment } from '@/domain/model';
import { calculateDay, dateKey, daysInMonth, formatDecimal, formatHours, formatMoney, formatNumber, isoWeek, monthKey, MONTHS, parseDateKey, parseHours, parseNumber, WEEKDAYS } from '@/domain/time';

export type MonthDay = { date: string; day: number; weekday: number; work: Employment['days'][string] | undefined; calculation: ReturnType<typeof calculateDay>; allowances: Employment['allowances'] };
export type MonthInfo = { key: string; days: MonthDay[]; net: number; worked: number; noPause: string[]; allowances: Employment['allowances'] };

export function getMonthInfo(employment: Employment, year: number, month: number): MonthInfo {
  const key = monthKey(year, month);
  const allowances = employment.allowances.filter((item) => item.date.startsWith(key));
  const days: MonthDay[] = [];
  let net = 0;
  let worked = 0;
  const noPause: string[] = [];
  for (let day = 1; day <= daysInMonth(year, month); day += 1) {
    const date = dateKey(year, month, day);
    const work = employment.days[date];
    const calculation = work ? calculateDay(work) : null;
    if (calculation) { net += calculation.net; worked += 1; if (calculation.pause === 0) noPause.push(date); }
    days.push({ date, day, weekday: new Date(year, month, day).getDay(), work, calculation, allowances: allowances.filter((item) => item.date === date) });
  }
  return { key, days, net, worked, noPause, allowances };
}

function allowanceTotal(info: MonthInfo, label: string) {
  const entries = info.allowances.filter((item) => item.label === label);
  return { quantity: entries.reduce((sum, item) => sum + item.quantity, 0), amount: entries.reduce((sum, item) => sum + (item.amount ?? 0), 0), hasAmount: entries.some((item) => item.amount !== null) };
}

export function MonthSummary({ employment, info, month }: { employment: Employment; info: MonthInfo; month: number }) {
  const theme = employmentColors[employment.color];
  return <View style={styles.summary}>
    <View style={[styles.summaryAccent, { backgroundColor: theme.main }]} />
    <Text style={styles.summaryCaption}>{employment.name} · {MONTHS[month]}</Text>
    <View style={styles.summaryValueRow}><Text style={styles.summaryValue}>{formatHours(info.net)}</Text><Text style={styles.summaryUnit}>Std</Text></View>
    <Text style={styles.summaryMeta}>{info.worked} {info.worked === 1 ? 'Arbeitstag' : 'Arbeitstage'}</Text>
  </View>;
}
function formatShortDate(key: string) { const date = parseDateKey(key); return `${WEEKDAYS[date.getDay()]} ${String(date.getDate()).padStart(2, '0')}.${String(date.getMonth() + 1).padStart(2, '0')}.`; }

export function DaysView({ employment, info, month, onOpenDay }: { employment: Employment; info: MonthInfo; month: number; onOpenDay: (date: string) => void }) {
  const [mode, setMode] = useState<'recorded' | 'all'>('recorded');
  const visible = info.days.filter((item) => mode === 'all' || item.calculation || item.allowances.length);
  const groups = visible.reduce<{ week: number; days: MonthDay[] }[]>((all, day) => { const week = isoWeek(parseDateKey(day.date)); const last = all.at(-1); if (!last || last.week !== week) all.push({ week, days: [day] }); else last.days.push(day); return all; }, []);
  return <>
    <MonthSummary employment={employment} info={info} month={month} />
    <SectionHeading right={<View style={styles.segment}><Segment active={mode === 'recorded'} label="Erfasst" onPress={() => setMode('recorded')} /><Segment active={mode === 'all'} label="Alle Tage" onPress={() => setMode('all')} /></View>}>Tage</SectionHeading>
    {!groups.length ? <Card><Text style={styles.empty}>In diesem Monat gibt es für „{employment.name}“ noch keine Einträge. Tippe auf das Plus, um deinen ersten Arbeitstag zu erfassen.</Text></Card> : <View style={styles.dayList}>{groups.map((group) => <View key={group.week} style={styles.week}><View style={styles.weekHeader}><Text style={styles.weekText}>KW {group.week}</Text><Text style={styles.weekText}>{formatHours(group.days.reduce((sum, day) => sum + (day.calculation?.net ?? 0), 0))} Std</Text></View>{group.days.map((day) => <DayCard day={day} key={day.date} onPress={() => onOpenDay(day.date)} />)}</View>)}</View>}
  </>;
}

function Segment({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[styles.segmentButton, active && styles.segmentActive]}><Text style={[styles.segmentText, active && styles.segmentTextActive]}>{label}</Text></TouchableOpacity>; }
function DayBadge({ day }: { day: MonthDay }) { const today = new Date(); const isToday = day.date === dateKey(today.getFullYear(), today.getMonth(), today.getDate()); const weekend = day.weekday === 0 || day.weekday === 6; return <View style={[styles.dayBadge, weekend && styles.weekendBadge, isToday && styles.todayBadge]}><Text style={[styles.badgeWeekday, isToday && styles.todayText]}>{WEEKDAYS[day.weekday]}</Text><Text style={[styles.badgeDay, isToday && styles.todayText]}>{String(day.day).padStart(2, '0')}</Text></View>; }
function DayCard({ day, onPress }: { day: MonthDay; onPress: () => void }) {
  const empty = !day.calculation && !day.allowances.length;
  const amount = day.allowances.reduce((sum, item) => sum + (item.amount ?? 0), 0);
  return <TouchableOpacity activeOpacity={0.75} onPress={onPress} style={[styles.dayCard, empty && styles.emptyDayCard]}><DayBadge day={day} /><View style={styles.dayMain}>{day.calculation && day.work ? <><Text style={styles.dayTitle}>{day.work.start} – {day.work.end}{day.calculation.overnight ? <Text style={styles.nextDay}>  +1 Tag</Text> : null}</Text>{day.calculation.pause === 0 ? <View style={styles.noPauseRow}><Ionicons color={colors.amber} name="ban-outline" size={15} /><Text style={styles.noPause}>Keine Pause</Text></View> : <Text style={styles.daySubtitle}>Pause {day.calculation.pause} min</Text>}<AllowanceChips allowances={day.allowances} note={day.work.note} /></> : day.allowances.length ? <><Text style={styles.dayTitle}>{[...new Set(day.allowances.map((item) => item.label))].join(' + ')}</Text><Text style={styles.daySubtitle}>Keine Arbeitszeit erfasst</Text></> : <Text style={styles.daySubtitle}>Nicht erfasst</Text>}</View>{day.calculation ? <View style={styles.net}><Text style={styles.netValue}>{formatHours(day.calculation.net)}</Text><Text style={styles.netUnit}>Std</Text></View> : amount ? <Text style={styles.netValue}>{formatMoney(amount)}</Text> : <Ionicons color="#9AA4BD" name="add" size={20} />}</TouchableOpacity>;
}
function AllowanceChips({ allowances, note }: { allowances: Employment['allowances']; note: string }) { if (!allowances.length && !note) return null; return <View style={styles.chips}>{allowances.map((item) => <View key={item.id} style={[styles.chip, item.label === 'Bereitschaft' ? styles.tealChip : item.label === 'Einspringen' ? styles.violetChip : null]}><Text style={[styles.chipText, item.label === 'Bereitschaft' ? styles.tealChipText : item.label === 'Einspringen' ? styles.violetChipText : null]}>{item.label === 'Einspringen' ? 'Eingesprungen' : item.label}{item.quantity !== 1 ? ` ×${formatNumber(item.quantity)}` : ''}</Text></View>)}{note ? <Text numberOfLines={1} style={styles.note}>{note}</Text> : null}</View>; }

export function AllowancesView({ info, employment, onOpen }: { info: MonthInfo; employment: Employment; onOpen: (id: string) => void }) {
  const others = [...new Set(info.allowances.map((item) => item.label).filter((label) => !MAIN_ALLOWANCES.includes(label as never)))];
  return <>
    <View style={styles.tiles}>{MAIN_ALLOWANCES.map((label) => { const total = allowanceTotal(info, label); const teal = label === 'Bereitschaft'; return <View key={label} style={[styles.tile, teal ? styles.tealTile : styles.violetTile]}><Text style={styles.tileLabel}>{label}</Text><Text style={styles.tileValue}>{formatNumber(total.quantity)}×</Text><Text style={styles.tileSub}>{total.hasAmount ? formatMoney(total.amount) : total.quantity ? 'ohne Betrag' : '–'}</Text></View>; })}</View>
    {others.length ? <Card><Text style={styles.cardCap}>Weitere Zulagen</Text>{others.map((label) => { const total = allowanceTotal(info, label); return <View key={label} style={styles.keyValue}><Text style={styles.kvLabel}>{label} · {formatNumber(total.quantity)}×</Text><Text style={styles.kvValue}>{total.hasAmount ? formatMoney(total.amount) : '–'}</Text></View>; })}</Card> : null}
    {!info.allowances.length ? <Card><Text style={styles.empty}>Noch keine Zulagen für „{employment.name}“ in diesem Monat. Tippe auf das Plus und wähle im Eintrag „Bereitschaft“ oder „Einspringen“ – mit oder ohne Arbeitszeit.</Text></Card> : <><SectionHeading>Einträge</SectionHeading><View style={styles.dayList}>{[...info.allowances].sort((a, b) => a.date.localeCompare(b.date)).map((allowance) => { const date = parseDateKey(allowance.date); const work = employment.days[allowance.date]; return <TouchableOpacity key={allowance.id} onPress={() => onOpen(allowance.id)} style={styles.dayCard}><View style={styles.dayBadge}><Text style={styles.badgeWeekday}>{WEEKDAYS[date.getDay()]}</Text><Text style={styles.badgeDay}>{String(date.getDate()).padStart(2, '0')}</Text></View><View style={styles.dayMain}><Text style={styles.dayTitle}><Text style={{ color: allowance.label === 'Bereitschaft' ? colors.teal : allowance.label === 'Einspringen' ? colors.violet : colors.accent }}>● </Text>{allowance.label}{allowance.quantity !== 1 ? ` ×${formatNumber(allowance.quantity)}` : ''}</Text><Text style={styles.daySubtitle}>{work ? `Arbeitszeit ${work.start}–${work.end}` : 'ohne Arbeitszeit'}</Text></View><Text style={styles.netValue}>{allowance.amount === null ? '–' : formatMoney(allowance.amount)}</Text></TouchableOpacity>; })}</View></>}
  </>;
}

export function getDeviationCount(employment: Employment, info: MonthInfo) {
  const billing = employment.billing[info.key];
  if (!billing) return 0;
  const labels = [...new Set([...MAIN_ALLOWANCES, ...info.allowances.map((item) => item.label), ...Object.keys(billing.allowances)])];
  const hourResult = compareValue(parseHours(billing.hours), info.net, 'Std');
  return (hourResult.status === 'bad' ? 1 : 0) + labels.filter((label) => compareAllowance(info, label, billing.allowances[label]).status === 'bad').length;
}

export function ReconciliationView({ employment, info, onBillingChange, onOpenDay }: { employment: Employment; info: MonthInfo; onBillingChange: (billing: Employment['billing'][string]) => void; onOpenDay: (date: string) => void }) {
  const existing = employment.billing[info.key] ?? { hours: '', allowances: {} };
  const [billing, setBilling] = useState(existing);
  const [newLabel, setNewLabel] = useState('');
  const labels = [...new Set([...MAIN_ALLOWANCES, ...info.allowances.map((item) => item.label), ...Object.keys(billing.allowances)])];
  const set = (next: typeof billing) => { setBilling(next); onBillingChange(next); };
  const hourResult = compareValue(parseHours(billing.hours), info.net, 'Std');
  const results = labels.map((label) => compareAllowance(info, label, billing.allowances[label]));
  const deviations = (hourResult.status === 'bad' ? 1 : 0) + results.filter((item) => item.status === 'bad').length;
  const checked = (hourResult.status === 'ok' ? 1 : 0) + results.filter((item) => item.status === 'ok').length;
  return <>
    <View style={[styles.status, deviations ? styles.statusBad : checked ? styles.statusOk : styles.statusIdle]}><View style={styles.statusIcon}><Ionicons color={deviations ? colors.bad : checked ? colors.ok : colors.ink2} name={deviations ? 'alert-outline' : checked ? 'checkmark' : 'git-compare-outline'} size={24} /></View><View style={{ flex: 1 }}><Text style={[styles.statusTitle, deviations ? { color: '#9B2620' } : checked ? { color: '#0B6B49' } : null]}>{deviations ? `${deviations} ${deviations === 1 ? 'Abweichung' : 'Abweichungen'} gefunden` : checked ? 'Bisher alles korrekt' : 'Abrechnung eintragen'}</Text><Text style={styles.statusSub}>{deviations ? 'Die markierten Positionen stimmen nicht mit deinen Einträgen überein.' : checked ? 'Alle bislang eingetragenen Positionen stimmen.' : 'Trag ein, was abgerechnet wurde. Abweichungen werden markiert.'}</Text></View></View>
    <Card><Text style={styles.cardCap}>Stunden</Text><View style={styles.compare}><View style={{ flex: 1 }}><Text style={styles.compareCap}>Erfasst</Text><Text style={styles.compareValue}>{formatHours(info.net)} <Text style={styles.compareUnit}>Std</Text></Text><Text style={styles.compareHint}>{formatDecimal(info.net)} dezimal</Text></View><View style={{ flex: 1 }}><Text style={styles.compareCap}>Abrechnung</Text><TextInput keyboardType="decimal-pad" onChangeText={(hours) => set({ ...billing, hours })} placeholder="–" style={styles.largeInput} value={billing.hours} /><Text style={styles.compareHint}>z. B. 168,50 oder 168:30</Text></View></View><Result {...hourResult} /></Card>
    {labels.map((label, index) => { const own = allowanceTotal(info, label); const billed = billing.allowances[label] ?? { quantity: '', amount: '' }; const result = results[index]; return <Card key={label}><View style={styles.allowanceHead}><Text style={styles.allowanceTitle}>{label}</Text>{own.quantity === 0 && !MAIN_ALLOWANCES.includes(label as never) ? <TouchableOpacity onPress={() => { const allowances = { ...billing.allowances }; delete allowances[label]; set({ ...billing, allowances }); }}><Text style={styles.remove}>Entfernen</Text></TouchableOpacity> : null}</View><View style={styles.grid}><Text /><Text style={styles.gridHead}>Erfasst</Text><Text style={styles.gridHead}>Abrechnung</Text><Text style={styles.gridLabel}>Anzahl</Text><Text style={styles.gridOwn}>{formatNumber(own.quantity)}×</Text><TextInput keyboardType="decimal-pad" onChangeText={(quantity) => set({ ...billing, allowances: { ...billing.allowances, [label]: { ...billed, quantity } } })} placeholder="–" style={styles.smallInput} value={billed.quantity} /><Text style={styles.gridLabel}>Betrag</Text><Text style={styles.gridOwn}>{own.hasAmount ? formatMoney(own.amount) : '–'}</Text><TextInput keyboardType="decimal-pad" onChangeText={(amount) => set({ ...billing, allowances: { ...billing.allowances, [label]: { ...billed, amount } } })} placeholder="0,00 €" style={styles.smallInput} value={billed.amount} /></View><Result {...result} /></Card>; })}
    <View style={styles.addPosition}><TextInput onChangeText={setNewLabel} placeholder="Weitere Position" style={[styles.smallInput, { flex: 1 }]} value={newLabel} /><TouchableOpacity onPress={() => { const name = newLabel.trim(); if (name && !billing.allowances[name]) { set({ ...billing, allowances: { ...billing.allowances, [name]: { quantity: '', amount: '' } } }); setNewLabel(''); } }} style={styles.addButton}><Text style={styles.addButtonText}>Hinzufügen</Text></TouchableOpacity></View>
    {info.noPause.length ? <Card><Text style={styles.cardCap}>Tage ohne Pause · {info.noPause.length}</Text>{info.noPause.map((date) => { const work = employment.days[date]; const calculation = calculateDay(work); return <TouchableOpacity key={date} onPress={() => onOpenDay(date)} style={styles.noPauseEntry}><Text style={styles.daySubtitle}>{formatShortDate(date)}</Text><Text style={styles.kvLabel}>{work.start} – {work.end}</Text><Text style={styles.kvValue}>{formatHours(calculation?.net ?? 0)} Std</Text></TouchableOpacity>})}<Text style={styles.empty}>Prüfe, ob die Abrechnung hier eine Pause abgezogen hat.</Text></Card> : null}
  </>;
}

function compareValue(billed: number | null, own: number, unit: string) { if (billed === null) return { status: 'idle' as const, message: '' }; const difference = billed - own; if (Math.abs(difference) <= 1) return { status: 'ok' as const, message: '' }; return { status: 'bad' as const, message: `Abrechnung: ${formatHours(Math.abs(difference))} ${unit} ${difference < 0 ? 'weniger' : 'mehr'} als erfasst` }; }
function compareAllowance(info: MonthInfo, label: string, billed?: { quantity: string; amount: string }) { const own = allowanceTotal(info, label); const billedQuantity = parseNumber(billed?.quantity ?? ''); const billedAmount = parseNumber(billed?.amount ?? ''); if (billedQuantity === null && billedAmount === null) return { status: 'idle' as const, message: '' }; const messages: string[] = []; if (billedQuantity !== null && Math.abs(billedQuantity - own.quantity) > 0.001) messages.push(`Anzahl: ${formatNumber(Math.abs(billedQuantity - own.quantity))} ${billedQuantity < own.quantity ? 'weniger' : 'mehr'} als erfasst`); if (billedAmount !== null && own.hasAmount && Math.abs(billedAmount - own.amount) > 0.004) messages.push(`Betrag: ${formatMoney(Math.abs(billedAmount - own.amount))} ${billedAmount < own.amount ? 'weniger' : 'mehr'} als erfasst`); return { status: messages.length ? 'bad' as const : 'ok' as const, message: messages.join('\n') }; }
function Result({ status, message }: { status: 'ok' | 'bad' | 'idle'; message: string }) { return <View style={styles.result}><View style={[styles.resultPill, status === 'ok' ? styles.resultOk : status === 'bad' ? styles.resultBad : styles.resultIdle]}><Text style={[styles.resultText, status === 'ok' ? { color: colors.ok } : status === 'bad' ? { color: colors.bad } : null]}>{status === 'ok' ? '✓ Stimmt' : status === 'bad' ? '! Abweichung' : 'Offen'}</Text></View>{message ? <Text style={styles.resultMessage}>{message}</Text> : null}</View>; }

const styles = StyleSheet.create({
  summary: { overflow: 'hidden', borderRadius: 24, padding: 20, backgroundColor: colors.card, ...shadow }, summaryAccent: { position: 'absolute', top: 0, bottom: 0, left: 0, width: 5 }, summaryCaption: { color: colors.muted, fontFamily: font.bold, fontSize: 13 }, summaryValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8, marginTop: 5 }, summaryValue: { color: colors.ink, fontFamily: font.extraBold, fontSize: 46, letterSpacing: -1.5 }, summaryUnit: { color: colors.muted, fontFamily: font.bold, fontSize: 17 }, summaryMeta: { color: colors.ink2, fontFamily: font.semiBold, fontSize: 14, marginTop: 2 },
  segment: { flexDirection: 'row', padding: 3, borderRadius: 12, backgroundColor: '#E3E7F1' }, segmentButton: { height: 34, paddingHorizontal: 10, borderRadius: 9, justifyContent: 'center' }, segmentActive: { backgroundColor: colors.card }, segmentText: { color: colors.muted, fontFamily: font.bold, fontSize: 11 }, segmentTextActive: { color: colors.ink }, empty: { color: colors.muted, fontFamily: font.medium, fontSize: 14, lineHeight: 20 },
  dayList: { gap: 8 }, week: { gap: 8 }, weekHeader: { paddingHorizontal: 6, paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' }, weekText: { color: colors.muted, fontFamily: font.bold, fontSize: 11, letterSpacing: 0.7, textTransform: 'uppercase' }, dayCard: { minHeight: 80, paddingVertical: 12, paddingLeft: 12, paddingRight: 16, borderRadius: 20, backgroundColor: colors.card, flexDirection: 'row', alignItems: 'center', gap: 14, ...shadow }, emptyDayCard: { backgroundColor: 'transparent', borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#C9D0E2', shadowOpacity: 0, elevation: 0 }, dayBadge: { width: 50, height: 56, borderRadius: 15, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, weekendBadge: { backgroundColor: '#E4E8F3' }, todayBadge: { backgroundColor: colors.accent }, badgeWeekday: { color: colors.muted, fontFamily: font.extraBold, fontSize: 11, textTransform: 'uppercase' }, badgeDay: { color: colors.ink, fontFamily: font.extraBold, fontSize: 20 }, todayText: { color: '#FFF' }, dayMain: { flex: 1, gap: 3 }, dayTitle: { color: colors.ink, fontFamily: font.extraBold, fontSize: 16 }, nextDay: { color: colors.muted, fontFamily: font.bold, fontSize: 11 }, daySubtitle: { color: colors.muted, fontFamily: font.semiBold, fontSize: 13 }, noPauseRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, noPause: { color: colors.amber, fontFamily: font.extraBold, fontSize: 13 }, net: { alignItems: 'flex-end' }, netValue: { color: colors.ink, fontFamily: font.extraBold, fontSize: 19 }, netUnit: { color: colors.muted, fontFamily: font.bold, fontSize: 11 }, chips: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6, marginTop: 4 }, chip: { minHeight: 24, borderRadius: 12, paddingHorizontal: 10, backgroundColor: colors.accentSoft, justifyContent: 'center' }, chipText: { color: colors.accentDeep, fontFamily: font.bold, fontSize: 11 }, tealChip: { backgroundColor: colors.tealSoft }, tealChipText: { color: '#075A61' }, violetChip: { backgroundColor: colors.violetSoft }, violetChipText: { color: '#4B2A9E' }, note: { maxWidth: 120, color: colors.muted, fontFamily: font.semiBold, fontSize: 11 },
  tiles: { flexDirection: 'row', gap: 12 }, tile: { flex: 1, borderRadius: 22, padding: 16, gap: 2 }, tealTile: { backgroundColor: colors.tealSoft }, violetTile: { backgroundColor: colors.violetSoft }, tileLabel: { color: colors.ink2, fontFamily: font.extraBold, fontSize: 13 }, tileValue: { color: colors.ink, fontFamily: font.extraBold, fontSize: 36 }, tileSub: { color: colors.ink2, fontFamily: font.bold, fontSize: 12 }, cardCap: { color: colors.muted, fontFamily: font.extraBold, fontSize: 12, letterSpacing: 0.8, textTransform: 'uppercase' }, keyValue: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, kvLabel: { color: colors.ink2, fontFamily: font.semiBold, fontSize: 14 }, kvValue: { color: colors.ink, fontFamily: font.extraBold, fontSize: 14 },
  status: { borderRadius: 24, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 }, statusBad: { backgroundColor: colors.badSoft }, statusOk: { backgroundColor: colors.okSoft }, statusIdle: { backgroundColor: '#E6EAF5' }, statusIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' }, statusTitle: { color: colors.ink2, fontFamily: font.extraBold, fontSize: 18 }, statusSub: { color: colors.ink2, fontFamily: font.semiBold, fontSize: 12 }, compare: { flexDirection: 'row', gap: 12 }, compareCap: { color: colors.muted, fontFamily: font.extraBold, fontSize: 11, letterSpacing: 0.7, textTransform: 'uppercase' }, compareValue: { color: colors.ink, fontFamily: font.extraBold, fontSize: 28, marginVertical: 7 }, compareUnit: { color: colors.muted, fontSize: 14 }, compareHint: { color: colors.muted, fontFamily: font.semiBold, fontSize: 11 }, largeInput: { height: 58, borderRadius: 12, backgroundColor: colors.soft, paddingHorizontal: 12, color: colors.ink, fontFamily: font.extraBold, fontSize: 25, marginVertical: 3 }, result: { gap: 6, alignItems: 'flex-start' }, resultPill: { height: 28, borderRadius: 14, paddingHorizontal: 12, justifyContent: 'center' }, resultOk: { backgroundColor: colors.okSoft }, resultBad: { backgroundColor: colors.badSoft }, resultIdle: { backgroundColor: colors.soft }, resultText: { color: colors.muted, fontFamily: font.extraBold, fontSize: 12 }, resultMessage: { color: colors.ink2, fontFamily: font.semiBold, fontSize: 12 }, allowanceHead: { flexDirection: 'row', justifyContent: 'space-between' }, allowanceTitle: { color: colors.ink, fontFamily: font.extraBold, fontSize: 17 }, remove: { color: colors.muted, fontFamily: font.bold, fontSize: 12 }, grid: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 }, gridHead: { width: '32%', color: colors.muted, fontFamily: font.extraBold, fontSize: 10, textTransform: 'uppercase' }, gridLabel: { width: '24%', color: colors.ink2, fontFamily: font.bold, fontSize: 13 }, gridOwn: { width: '29%', color: colors.ink, fontFamily: font.extraBold, fontSize: 15 }, smallInput: { width: '38%', height: 44, borderRadius: 12, backgroundColor: colors.soft, paddingHorizontal: 10, color: colors.ink, fontFamily: font.bold, fontSize: 14 }, addPosition: { flexDirection: 'row', gap: 8 }, addButton: { height: 44, borderRadius: 14, backgroundColor: colors.soft, paddingHorizontal: 14, justifyContent: 'center' }, addButtonText: { color: colors.ink, fontFamily: font.extraBold, fontSize: 13 }, noPauseEntry: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderTopWidth: 1, borderTopColor: colors.line },
});
